Revert "Downgrade puma to 4.x series versions, because otherwise"
This reverts commit adaee3ff2ba9c0ba4071c1b0093eb53e3929f557.

Revert Puma downgrade.  Our problem is not this either, but I
really do not know what it is.  Sometimes it happens, sometimes
it does not.  But now it happened with Puma 4.3.7 as well.

The issue looks like this in the puavo-rest logs:

  UNHANDLED EXCEPTION (UUID ikglscdmqtzxyeafvnpwburhj): undefined method `clean_up' for nil:NilClass
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/puma-4.3.7/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/puma-4.3.7/lib/puma/server.rb:328:in `block in run'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/puma-4.3.7/lib/puma/server.rb:472:in `process_client'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/puma-4.3.7/lib/puma/server.rb:713:in `handle_request'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/puma-4.3.7/lib/puma/configuration.rb:228:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-2.1.2/lib/rack/null_logger.rb:11:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
  /var/app/puavo-rest/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'